# Generated by Django 6.0.5 on 2026-05-14 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('beach', 'Beach'), ('hill', 'Hill'), ('forest', 'Forest'), ('historical', 'Historical'), ('lake', 'Lake'), ('city', 'City')], max_length=20)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField()),
                ('best_months', models.JSONField(default=list)),
                ('avoid_months', models.JSONField(default=list)),
                ('monsoon_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('flood_risk', models.BooleanField(default=False)),
                ('road_access_monsoon', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('weather_city_id', models.CharField(max_length=100)),
                ('images', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('min_days_recommended', models.IntegerField(default=1)),
                ('max_days_recommended', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('launch', 'Launch'), ('flight', 'Flight'), ('cng', 'CNG'), ('microbus', 'Microbus')], max_length=20)),
                ('operator', models.CharField(max_length=255)),
                ('avg_duration_minutes', models.IntegerField()),
                ('avg_cost_bdt', models.IntegerField()),
                ('booking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('duration_hours', models.FloatField()),
                ('cost_bdt', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('food', 'Food')], max_length=20)),
                ('best_time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('any', 'Any')], max_length=20)),
                ('is_monsoon_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('star_rating', models.IntegerField(default=1)),
                ('price_per_night_bdt', models.IntegerField()),
                ('price_tier', models.CharField(choices=[('budget', 'Budget'), ('midrange', 'Midrange'), ('premium', 'Premium')], max_length=20)),
                ('amenities', models.JSONField(default=list)),
                ('booking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('agoda_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('avg_meal_cost_bdt', models.IntegerField()),
                ('price_tier', models.CharField(choices=[('budget', 'Budget'), ('midrange', 'Midrange'), ('premium', 'Premium')], max_length=20)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='destinations.destination')),
            ],
        ),
    ]
